### ISSUE TITLE
create an updater option

### ISSUE THREAD

**Issue by aelsharawi** [wpbullet/WP-Bullet-VPS-Installer#5]
what happens if the installer installed over an old vps that the installer was used on it before?

**Comment by wpbullet** [comment]
it won't work because it assumes it's a fresh install. I am thinking about how to adapt it so it can create new sites.

I was thinking it would prompt for the mysql root password and then the rest of the variables it does on first run, check if apache is installed and make the vhost in the right folder, otherwise put it in nginx vhost folder.

I would also need to rearrange the parameters for nginx so the fastcgi cache and request zones are in separate files
